### ISSUE TITLE
tower

### ISSUE THREAD

**Issue by elibsora** [capajon/r6maps#101]
hi man, there in no tower map in this really gfreat and comfortable tool, is there one coming?
can i help in any way?

**Comment by capajon** [comment]
Hey, sorry I have been a bit busy for the last few weeks, I plan to do this in the next few days, even if just an initial incomplete version.

**Comment by elibsora** [comment]
great, ive done some of my own work, didnt know u would answer so quicklty,
u can use this freely, the pictures in the background are not mine but are
from reddit:
https://docs.google.com/drawings/d/1Zp7OZaqKRo4bzs_df0KiCYTjCY3Sr45NhYuIP0nebYQ/edit
dont have al lthe objectives, but i think this works to some extent.


--
אלי גלוחוב
0526105411

2017-12-13 17:17 GMT+02:00 Jon Capa <notifications@github.com>:

**Comment by appleparan** [comment]
I was wondering, too. Ready for translation!

**Comment by elibsora** [comment]
what do u mean by "translation"?


--
אלי גלוחוב
0526105411

2017-12-14 6:19 GMT+02:00 appleparan <notifications@github.com>:

**Comment by appleparan** [comment]
Korean translation

Liam Jongsu Kim

**Comment by capajon** [comment]
Should at least be available for translations now!  Working on a few changes before an initial release.  Will then follow up with a more detailed map.

**Comment by elibsora** [comment]
hi man, if ur still in the map business. id like to help in whatever is
needed, i hope my past work helped you and i can do that for the new map
aswell

--
אלי גלוחוב
0526105411


‫בתאריך יום ד׳, 13 בדצמ׳ 2017 ב-17:17 מאת ‪Jon Capa‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by capajon** [comment]
Hey, thanks!  I've been taking a break from the site other than keeping it running, but yes, we're back in business. :) I could use help if you are up for it.  What I'd like to do is get the base images going (it takes some editing of screen shots from in game, unless you know how to export Ubi's game files?).  I won't have time to do that form the TTS today, but should tomorrow.  Will keep you updated.  Once I have those base images we can start populating with room names and what not.

**Comment by elibsora** [comment]
i dont know how to get those files... but i can help with names, drone
spots, cameras, whatever...

--
אלי גלוחוב
0526105411


‫בתאריך יום ג׳, 22 במאי 2018 ב-23:34 מאת ‪Jon Capa‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by elibsora** [comment]
this is the best i could, i can add all the cams and drone homes.
this is fine?
https://docs.google.com/drawings/d/1vCfb6EJqBtUzNMGdaLH9BEKczuYigrQDcum-2RaBLIg/edit

--
אלי גלוחוב
0526105411


‫בתאריך יום ג׳, 22 במאי 2018 ב-23:48 מאת אלי גלוחוב <‪elibsora@gmail.com
‬‏>:‬
