### ISSUE TITLE
Missing Border map

### ISSUE THREAD

**Issue by mvy** [capajon/r6maps#12]
Hello!

Very nice job on the r6maps site. Do you intend to put the Border map which is currently missing?

I do not know if I have time, but do you need help to do so?

**Comment by capajon** [comment]
@mvy Hey sorry I didn't reply.  I was waiting for Ubisoft to update their tactical board with Border as I use their base map images.  At first I thought it would happen sooner.  From now on for new maps I will probably at least do something rough to start with in-game screens.

Anyway, Border is now updated. :)
