### ISSUE TITLE
Dining room floor in House towards garage is non breakable

### ISSUE THREAD

**Issue by arienvanhelden** [capajon/r6maps#24]
But on the map it says it is destroyable

**Comment by capajon** [comment]
Thanks - will address this.  It is a bit of a pain to update because I am using Ubisoft's images from their tactics board, so I'll have to spend some time editing it manually...

**Comment by appleparan** [comment]
or you can make wiki or issue page about map errors, because I found bank map start point 'sewer access'  is not exists. It is 'jewerly front'
