### ISSUE TITLE
[Suggestion] Add Floating Compass

### ISSUE THREAD

**Issue by Sir-Will** [capajon/r6maps#26]
Hey,
it would be great if the maps have a floating compass which is visible all the time while moving the map.
Very useful for call outs.

**Comment by capajon** [comment]
Hey, thanks for the suggestion!  So, the map never rotates in the site so north is always pointing to the top.  You think the compass would just be a handy reminder?

**Comment by Sir-Will** [comment]
Oh, right.
Yea, would be good as reminder. Doesn't need to be big, maybe the in game one at the bottom right corner and toggleable.

**Comment by capajon** [comment]
I'm going to try putting something on each map in a noticeable but non-static position (ie as you pan, the compass will pan away too).  That way it is a reminder, but doesn't clutter up each view, and won't require a new option in the menu (which I don't want to have too many of if possible).   I'll comment here once that is in.
