### ISSUE TITLE
Localization problems

### ISSUE THREAD

**Issue by Kondra007** [capajon/r6maps#29]
Hi there! I've started working on Russian translation for R6Maps website.
Added `r6-maps.lang-terms.ru.js` file, added it to `index.html` as script and ran local webserver.

However, all other languages except Russian are now missing in Options. 
What I have done wrong?

**Comment by Kondra007** [comment]
Ouch, my bad, used wrong file as template. Fixed.

**Comment by capajon** [comment]
BTW, thanks for working on this!  I'll be very excited to see Russian translations.

If you have any more issues let me know.  

Here's an example PR for Korean translations that were done recently, it is a good reference IMO: https://github.com/capajon/r6maps/pull/27

Looks like I should start considering properly minimizing and combining the js asset files now... :)

**Comment by MasterGroosha** [comment]
@capajon There's one question (for now): what are "Line of sight walls" and "Line of sight floors"?

From what I see, "Line of sight floors" are simply wooden floors which can be partially destroyed.
But what about "Line of sight walls"?

**Comment by capajon** [comment]
I think either they are half walls that you can see over.... or they are walls that are destructible but that you can only destroy to the point where you can shoot through them, but you can never walk through them.  There are a few like that I believe that have steel beams that can't even be C4'd.

I'm not 100% sure though.  That's my interpretation.  Those were originally marked on the ubisoft images that I started from... although for the newer maps I had to mark them myself so not sure I am 100% consistent with what Ubisoft did (or that Ubisoft was consistent between maps either in the first place).

Hope that helps.

**Comment by MasterGroosha** [comment]
@capajon This helps a lot, thanks!
