### ISSUE TITLE
Missing "Caterer" area on Plane?

### ISSUE THREAD

**Issue by MasterGroosha** [capajon/r6maps#31]
This place is named as "Caterer" (in Russian) on Plane map. However, on your map it's missing.
Bug or feature?
![image](https://cloud.githubusercontent.com/assets/2780044/21073239/ddfaa7d0-bee9-11e6-83a3-0f44408b763f.png)

Edit: There's another Caterer section near pilot cabin, so both of them are Caterer, right?

**Comment by capajon** [comment]
You're right, will be fixed shortly. :)
