### ISSUE TITLE
Missing "Showers hallway" on Kanal

### ISSUE THREAD

**Issue by MasterGroosha** [capajon/r6maps#33]
In current version (and at least with Russian localization) the selected area (marked as red) is "Showers Hallway" 
![image](https://cloud.githubusercontent.com/assets/2780044/21129465/b65bc620-c112-11e6-9ea3-6ad824a9cfe9.png)

**Comment by capajon** [comment]
@appleparan

Also see issue #34 which is related.  Two room names were missing that are added now and could use Korean translations if you have time (thank you :).  I'll look for the German and French translations for the two rooms.

Also, I'll be adding Bartlett University soon after it is released so keep an eye out for that if you are up for doing that too.
