### ISSUE TITLE
Cannot build with npm

### ISSUE THREAD

**Issue by MasterGroosha** [capajon/r6maps#60]
1) At least for me, I had to manually setup uglify-js (wasn't included in `npm i`?), otherwise all builds failed
2) Still can't build CSS files. On Windows 10 I keep getting "scss is not external or internal command...", and no scss-related binaries are found. Installing `node-sass` didn't help and there's no relevant package "scss".

**Comment by MasterGroosha** [comment]
And the same on Lubuntu 16.10

**Comment by capajon** [comment]
As we discussed, a quick workaround for now is to just download the latest css from the site if you don't need to make css changes (e.g. the current latest version is http://www.r6maps.com/css/main.1.2.10.css).  Pop that into site/css

I'll have to look into what is needed.  It might be ruby+sass gem.  I haven't tried running all this on a fresh Windows PC but I'll do that soon and update the steps that are really required.

**Comment by capajon** [comment]
More info on uglify-js

"Dependencies are missing an uglify-js (or how it's named) module. Having errors both on Windows/Lubuntu. Manual installation of this module fixes the problem"

**Comment by capajon** [comment]
Quick update: I'm still going to update the readme with better instructions, setting this up right now on a fresh PC.

**Comment by capajon** [comment]
The readme has much better instructions now.  @MasterGroosha if you still can't build though please let me know.

**Comment by MasterGroosha** [comment]
Thanks for the new instructions. I'll try in the weekend
