### ISSUE TITLE
Favela missing line of sight wall in stair hall

### ISSUE THREAD

**Issue by tristnj** [capajon/r6maps#70]
First-floor stair hall has a line of sight wall on the east looking into Biker's Apartment.

![satanslair](https://cloud.githubusercontent.com/assets/24313799/24135341/326f83ee-0dd7-11e7-82ac-1c6f4eabadf6.jpg)

![insidesatanslair](https://cloud.githubusercontent.com/assets/24313799/24135338/2d15afe0-0dd7-11e7-84e5-c4411ce52f09.jpg)

**Comment by capajon** [comment]
Good catch thanks, I'll make sure to fix this in the next couple of days.
