### ISSUE TITLE
R6maps.com will not load up on my tablet

### ISSUE THREAD

**Issue by Cordypants** [capajon/r6maps#76]
Website will not load up on Chrome for some reason. I've cleared my cache and all sorts but it's just not having it. Is there any work being carried out on the site? Any help would be much appreciated.

**Comment by capajon** [comment]
Yes the site was down for approximately 3 hours Saturday according to some site monitoring.  That's pretty unusual, the site is rarely down.  I don't think it is a tablet specific issue.  Let me know if the site is still not working for you though @Cordpants.  Thanks!  Closing for now.
