### ISSUE TITLE
Roof vents on Coastline

### ISSUE THREAD

**Issue by j-hibbard** [capajon/r6maps#80]
Video of the vents in question https://gfycat.com/ParallelParchedDevilfish

Seems like a great addition to your maps to figure out where these drop grenades on to the floor below.

**Comment by capajon** [comment]
Hey I did try to represent these actually as drone tunnels.  If you look on the roof there are two drone tunnels in these locations with a down arrow (and then on the second floor it is a down/up arrow combo, and then on the first floor an up arrow).  It is confusing though, I think?  I was reluctant to create a whole new icon just for two of these (they don't appear on any other maps yet) but I bet we'll see these again in new maps.

@j-hibbard  What do you think?

**Comment by j-hibbard** [comment]
Ah I didn't notice that because the one in the video is looks like it might be missing (Correct me if I'm wrong) The video shows a grenade vent near the top left roof hatch above Hall of Fame.

The denotation might be a bit confusing, not being the most familiar with the map I just figured it was denoting a drone hole between the DJ booth and the wall, but I see them now that you point it out.

**Comment by capajon** [comment]
I think you're right, that one is missing!  I will at least add that one, and consider a new icon.
