### ISSUE TITLE
Breakable Windows 

### ISSUE THREAD

**Issue by AJHughs** [capajon/r6maps#89]
Hey I love the site you made its amazing one request I have though is on maps you cannot tell which windows are breakable and which are sealed up and cannot be broken this would be a great help to be able to quickly see where a good spot to enter a building. For example on Bartlett University on the north side of the Trophy room there are three windows and only one is breakable and as it is now you cant tell that by looking at the R6Maps site 

Keep up the great work 

Hughs

**Comment by capajon** [comment]
@AJHughs Thanks for the suggestion.  I like the idea and I think I should be able to implement it.  Would you be willing to help identify what each window is (just some rough marked up screen shots of the floors would do). 

Things are a little 'busy' for me in the summer right now but if I had help with that I could probably get this released within a few weeks or so.

**Comment by AJHughs** [comment]
Would love to help but unfortunately due to Operation Health I can no longer go into custom games to look at each window as I have a strict NAT Type which I cannot change

**Comment by capajon** [comment]
Yeah I heard about that NAT thing and it sucks. :(  Well, I still like the suggestion and will try to get to it eventually, if anyone reading this wants to help out please speak up too! :)

**Comment by capajon** [comment]
Adding this to the README as a shor-term item to be worked on, hopefully in the next month or two.  Closing this in the meantime.
