### ISSUE TITLE
Bartlett Hostage is in the wrong place

### ISSUE THREAD

**Issue by purechaose** [capajon/r6maps#97]
Hostage in Bartlett cannot spawn in reading room (or at least, cannot be picked by the defenders as a spawn point). The fourth hostage location is in Main Office on the second floor, just south of the desk.

Edit: After messing with the html source of the website, it appears that the hostage location specified here: https://github.com/capajon/r6maps/blob/b35883af967108b1a5a8af68626401c55956d8ac/dev/js/main/main.map-data.js#L225
(or wherever that is actually specified in the end) and replaced with 
```
{ floor: 2, top: 265, left: 336}
```
give or take a few pixels.

**Comment by capajon** [comment]
Thanks for the fix. :)
