### ISSUE TITLE
what's the version of the uglify-js ?

### ISSUE THREAD

**Issue by nbuu** [capajon/r6maps#98]
in the site folder,  try "  npm run build:js   "   , but i get the error 

Supported options:
  content         null
  filename        null
  includeSources  false
  root            null
  url             null
ERROR: `./site/js/release.2.2.7/common.min.js.map` is not a supported option
    at DefaultsError.get (eval at <anonymous> (/usr/local/lib/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:79:23)

**Comment by purechaose** [comment]
This project uses UglifyJS2. If you have UglifyJS3, `build:js:common`, `build:js:main`, `build:js:about`, and `build:js:stats` scripts in package.json should be switched to the following:
```
    "build:js:common": "npm run build:js:mkdir && uglifyjs --compress --mangle -o ./site/js/release.2.2.7/common.min.js --source-map  \"filename='./site/js/release.2.2.7/common.min.js.map', url='common.min.js.map', includeSources=true\" ./dev/js/common/common.global.js ./dev/js/common/common.helpers.js ./dev/js/lang-terms/lang-terms.js ./dev/js/lang-terms/lang-terms.*.js",
    "build:js:main": "npm run build:js:mkdir && uglifyjs --compress --mangle -o ./site/js/release.2.2.7/main.min.js --source-map  \"filename='./site/js/release.2.2.7/main.min.js.map', url='main.min.js.map', includeSources=true\" ./dev/js/main/main.map-data.js ./dev/js/main/main.map-render.js ./dev/js/main/main.controls.js ./dev/js/main/main.select-maps.js ./dev/js/main/main.drawing.js ./dev/js/main/main.sessions.js ./dev/js/main/main.js",
    "build:js:about": "npm run build:js:mkdir && uglifyjs --compress --mangle -o ./site/js/release.2.2.7/about.min.js --source-map \"filename='./site/js/release.2.2.7/about.min.js.map', url='about.min.js.map', includeSources=true\" ./dev/js/about/about.js",
    "build:js:stats": "npm run build:js:mkdir && uglifyjs --compress --mangle -o ./site/js/release.2.2.7/stats.min.js --source-map \"filename='./site/js/release.2.2.7/stats.min.js.map', url='stats.min.js.map', includeSources=true\" ./dev/js/stats/stats.meta-data.js ./dev/js/stats/stats.render.js ./dev/js/stats/stats.controls.js ./dev/js/stats/stats.operators.data.js ./dev/js/stats/stats.map.data.js ./dev/js/stats/stats.api.js ./dev/js/stats/stats.map.render.js ./dev/js/stats/stats.operators.render.js ./dev/js/stats/stats.operators.chart.js ./dev/js/stats/stats.js"
```
You can also manually make the same fix bby looking at the UglifyJS3 [API](https://github.com/mishoo/UglifyJS2#command-line-usage), and noting that:
- `--source-map` in UglifyJS2 is the `filename` option for `--source-map` in UglifyJS3
- `--source-map-url` in UglifyJS2 is the `url` option for `--source-map` in UglifyJS3
- `--source-map-include-sources --` in UglifyJS2 is the same as setting the `includeSources` option to `true` for `--source-map` in UglifyJS3
I'll be setting up a PR for this soon.

**Comment by capajon** [comment]
Thanks for the fix. :)
